# Generated by Django 5.2.1 on 2025-07-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_code', models.CharField(max_length=255, unique=True)),
                ('quantity_meta', models.IntegerField(default=0)),
                ('quantity_planned', models.IntegerField(default=0)),
                ('quantity_completed', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='empty', max_length=20)),
            ],
        ),
    ]
