# Generated by Django 5.2.1 on 2025-07-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('production_lines', '0001_initial'),
        ('production_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plan_code', models.CharField(max_length=255, unique=True)),
                ('production_day', models.DateField()),
                ('shifts', models.JSONField(blank=True, null=True)),
                ('total_quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('in_progress', 'Em Progresso'), ('completed', 'Concluído'), ('paused', 'Pausado'), ('canceled', 'Cancelado')], default='planned', max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('planned', 'Planejado'), ('in_progress', 'Em Progresso'), ('completed', 'Concluído'), ('paused', 'Pausado'), ('canceled', 'Cancelado')], max_length=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production_order.productionorder')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='production_lines.productionline')),
            ],
            options={
                'verbose_name': 'Production Plan',
                'verbose_name_plural': 'Production Plans',
            },
        ),
    ]
