services:
  backend:
    build: 
      context: .               
      dockerfile: ./docker/Dockerfile
    image: django-image
    container_name: backend-api
    restart: unless-stopped
    entrypoint: /entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./docker/.env
    depends_on:
      clickhouse:
        condition: service_healthy
    labels:
      - "io.portainer.accesscontrol.public=true"
    networks:
      - app-network

  frontend:
    image: node:20
    container_name: react-web
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/src/assets:/app/src/assets
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    labels:
      - "io.portainer.accesscontrol.public=true"
    networks:
      - app-network
    
  postgres:
    image: postgres:15
    container_name: postgresdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    labels:
      - "io.portainer.accesscontrol.public=true"
    networks:
      - app-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    env_file:
      - ./docker/.env
    ports:
      - "9001:9000"
      - "8123:8123" 
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/clickhouse_init/create_user.sh:/docker-entrypoint-initdb.d/create_user.sh
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host", "localhost", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 15
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  clickhouse_data:
    driver: local

networks:
  app-network:
    driver: bridge
