# Generated by Django 5.2.1 on 2025-07-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_defect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productiondefect',
            options={'ordering': ['id']},
        ),
    ]
