# Generated by Django 5.2.1 on 2025-07-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('qtd_stations', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('inactive', 'Parada'), ('active', 'Operacional'), ('maintenance', 'Manutenção')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLineCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('capacity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_capacities', to='product.product')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='production_lines.productionline')),
            ],
            options={
                'verbose_name': 'Capacidade da Linha de Produção',
                'verbose_name_plural': 'Capacidades das Linhas de Produção',
                'unique_together': {('production_line', 'product', 'date')},
            },
        ),
    ]
