# Generated by Django 5.2.1 on 2025-07-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.JSONField()),
                ('current_status', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('num_employees', models.IntegerField()),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='production_lines.productionline')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
